apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-db-injector.fullname" . }}-renewer
  annotations:
    allow-replicacount-one: "true"
  labels:
  {{- include "vault-db-injector.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vaultDbInjector.renewer.replicas }}
  selector:
    matchLabels:
      app: vault-db-renewer
    {{- include "vault-db-injector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: vault-db-renewer
      {{- include "vault-db-injector.selectorLabels" . | nindent 8 }}
      annotations:
        logging.active: "true"
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - args: {{- toYaml .Values.vaultDbInjector.renewer.args | nindent 8 }}
        image: {{ .Values.vaultDbInjector.renewer.image.repository }}:{{ .Values.vaultDbInjector.renewer.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.vaultDbInjector.renewer.imagePullPolicy }}
        name: vault-db-renewer
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8888
          name: healthcheck
          protocol: TCP
        resources: {}
        securityContext: {{- toYaml .Values.vaultDbInjector.renewer.containerSecurityContext | nindent 10 }}
        volumeMounts:
          - mountPath: /renewer
            name: config-renewer
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: healthcheck
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: healthcheck
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      imagePullSecrets:
      - name: registry-token
      serviceAccountName: {{ include "vault-db-injector.fullname" . }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "vault-db-injector.fullname" . }}-renewer
          name: config-renewer