name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker buildx build \
          --file Dockerfile \
          --tag ${{ secrets.DOCKER_USERNAME }}/$GITHUB_REPOSITORY:${{ github.ref_name }} \
          --cache-from type=local,src=$HOME/.docker/.cache \
          --cache-to type=local,dest=$HOME/.docker/.cache \
          --platform linux/amd64,linux/arm64 \
          --push .

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
