package k8s

// NRIMapping is the JSON payload attached to a pod under
// ANNOTATION_NRI_MAPPING when the webhook admits a pod in NRI mode.
//
// The webhook ONLY stores metadata about the credential request — never
// a Vault token. The NRI plugin authenticates to Vault as itself at
// CreateContainer time, re-authorizes the pod against Vault's
// CanIGetRoles, and creates the dynamic credentials. Eliminates the
// "wrap-token-as-bearer-credential" exfiltration vector closed in Hunter
// finding #H5.
//
// Schema versioning: SchemaVersion controls the parser's strictness.
// Plugins newer than the webhook tolerate older annotations; plugins
// older than the webhook reject SchemaVersion they do not understand.
type NRIMapping struct {
	// SchemaVersion is the annotation schema. Always 2 for the pull-not-push
	// design. Schema 1 (wrap_token-based) is no longer accepted.
	SchemaVersion int `json:"schema,omitempty"`

	// DbPath is the Vault database secret engine mount path
	// (e.g. "databases").
	DbPath string `json:"db_path"`

	// DbRole is the Vault database role name to issue credentials for.
	DbRole string `json:"db_role"`

	// Placeholders maps each placeholder string injected into env vars to
	// the field name in the credential payload (typically "username" or
	// "password").
	Placeholders map[string]string `json:"placeholders"`

	// RequestID is a UUID generated by the webhook for traceability across
	// admission, plugin substitution, and lease lifecycle. Useful in logs;
	// not security-critical.
	RequestID string `json:"request_id,omitempty"`

	// PodNamespace and PodServiceAccount are stamped by the webhook so the
	// plugin can verify the pod identity it sees from NRI matches what the
	// webhook authorized. Defense against annotation-shape forgery (e.g.
	// a controller with pods.update but not serviceaccounts/token create).
	PodNamespace      string `json:"pod_namespace,omitempty"`
	PodServiceAccount string `json:"pod_service_account,omitempty"`
}
