{
 "title": "vault-db-injector",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(k8s_cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Last Synchronization Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vdbi_last_synchronization_duration_sum{k8s_cluster=~\"$cluster\"}) / sum(vdbi_last_synchronization_duration_count{k8s_cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Synchronization",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vdbi_last_synchronization_success{k8s_cluster=~\"$cluster\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Unauthorized SA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(vdbi_service_account_denied_count{k8s_cluster=~\"$cluster\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Store/Delete Operations",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(vdbi_store_data_count_success[$__rate_interval])))",
     "legendFormat": "Store Success"
    },
    {
     "expr": "round(sum(increase(vdbi_store_data_count_error[$__rate_interval])))",
     "legendFormat": "Store Error"
    },
    {
     "expr": "round(sum(increase(vdbi_delete_data_count_success[$__range])))",
     "legendFormat": "Delete Success"
    },
    {
     "expr": "round(sum(increase(vdbi_delete_data_count_error[$__range])))",
     "legendFormat": "Delete Error"
    }
   ]
  },
  {
   "title": "Total Revoke Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vdbi_revoke_token_count_error{k8s_cluster=~\"$cluster\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Renew Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vdbi_renew_token_count_error{k8s_cluster=~\"$cluster\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Data Stored Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vdbi_store_data_count_error{k8s_cluster=~\"$cluster\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Data Deleted Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vdbi_delete_data_count_error{k8s_cluster=~\"$cluster\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Operations Success/Failure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(vdbi_renew_token_count_success[$__rate_interval])))",
     "legendFormat": "Renew Success"
    },
    {
     "expr": "round(sum(increase(vdbi_renew_token_count_error[$__rate_interval])))",
     "legendFormat": "Renew Error"
    },
    {
     "expr": "round(sum(increase(vdbi_revoke_token_count_success[$__rate_interval])))",
     "legendFormat": "Revoke Success"
    },
    {
     "expr": "round(sum(increase(vdbi_revoke_token_count_error[$__rate_interval])))",
     "legendFormat": "Revoke Error"
    }
   ]
  },
  {
   "title": "Lease Operations Success/Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(vault_db_renew_sidecar_lease_renews[$__rate_interval])))",
     "legendFormat": "Renew Success"
    },
    {
     "expr": "round(sum(increase(vault_db_renew_sidecar_lease_renew_error[$__rate_interval])))",
     "legendFormat": "Renew Error"
    }
   ]
  },
  {
   "title": "Service Account Authorizations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(vdbi_service_account_authorized_count[$__rate_interval])))",
     "legendFormat": "Authorized"
    },
    {
     "expr": "round(sum(increase(vdbi_service_account_denied_count[$__rate_interval])))",
     "legendFormat": "Denied"
    }
   ]
  },
  {
   "title": "LeaseId Expiration",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vdbi_lease_expiration{k8s_cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Expiration",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vdbi_token_expiration{k8s_cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}