apiVersion: v1
name: vault-db-injector
version: 3.0.2  # x-release-please-version
appVersion: 3.0.2  # x-release-please-version
description: vault-db-injector helm chart
keywords:
- vault-db-injector
- vault
sources:
- https://github.com/numberly/vault-db-injector
maintainers:
- name: Guillaume LEGRAIN
  email: guillaume.legrain@numberly.com
engine: gotpl
